### ISSUE TITLE
Navbar Search Button Incorrectly Aligned

### ISSUE THREAD

**Issue by smalls12** [smalls12/km-forums#28]
The `Search` button on the navbar doesn't have the same height as the input box. A hacky fix seems to be to set `line-height: 1.45` on the button.

**Comment by smalls12** [comment]
This issue so far only appears to affect Chrome

**Comment by smalls12** [comment]
A solution seems to be to specify the `height` as well as `line-height` css properties. Taken from [here](http://stackoverflow.com/a/7229945/3762084)

**Comment by bsuto** [comment]
It's like one pixel off in Safari too
![screen shot 2016-01-19 at 8 21 51 am](https://cloud.githubusercontent.com/assets/1727027/12419701/bd4c4cf6-be85-11e5-8783-9a33ac08efb5.png)
