### ISSUE TITLE
Update Editing Interface

### ISSUE THREAD

**Issue by smalls12** [smalls12/km-forums#30]
The current editor is outdated which is especially problematic on smaller screens due to not scaling well. It would be nice to either roll our own editor, or use a more modern one. Creating a custom editor could be especially helpful if attaching files (#26) becomes a feature.

**Comment by bsuto** [comment]
How about Trix, by Basecamp?
https://github.com/basecamp/trix

**Comment by smalls12** [comment]
@bsuto I took a look at that, but the interface still doesn't scale well to smaller screens like phones. I'm thinking of moving to styling using markdown. Markdown is used by github, reddit, and stackexchange for formatting, and it doesn't involve using a toolbar to modify formatting. What do you think?

**Comment by bsuto** [comment]
Good call on using something responsive. Markdown is great, because it's there for people who want to style (and those people will probably "get" it) and invisible to people who don't.
